---
title: "Appunti di Fisica Nucleare e Subnucleare"
author: "Niccolò Zanotti"
date: "`r Sys.Date()`"
output:
  tufte::tufte_book:
    toc: yes
    citation_package: natbib
    latex_engine: xelatex
    includes:
      in_header: preamble.sty
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
    includes:
      in_header: preamble.sty
  tufte::tufte_html: default
  pdf_document:
    includes:
      in_header: preamble.sty
    toc: yes
subtitle: Prof. Nicola Semprini Cesari
runningheader: Appunti di Fisica Nucleare e Subnucleare
bibliography: bibliography.bib
link-citations: yes
link-at-notes: true
knit: (function(inputFile, encoding) {
      out_dir <- "output";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path("./",dirname("appunti-nucleare"), out_dir))})
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(echo = TRUE)
```

```{r, child=c('chapters/introduzione.Rmd', 'chapters/nucleare.Rmd','chapters/nucleo.Rmd','chapters/modelli-nucleari.Rmd')}
```

```{r, child=c('chapters/appendice.Rmd')}
```

# References

```{r bib, include=FALSE}
# create a bib file for the R packages used in this document
knitr::write_bib(c('base', 'rmarkdown'), file = 'bibliography.bib')
```
