---
title: "Appunti di Fisica Nucleare e Subnucleare"
author: "Niccolò Zanotti"
date: "`r Sys.Date()`"
output:
  tufte::tufte_book:
    toc: yes
    citation_package: natbib
    latex_engine: xelatex
    includes:
      in_header: ../preamble.sty
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
    includes:
      in_header: preamble.sty
  tufte::tufte_html: default
  pdf_document:
    includes:
      in_header: preamble.sty
    toc: yes
subtitle: Prof. Nicola Semprini Cesari
runningheader: Appunti di Fisica Nucleare e Subnucleare
bibliography: bibliography.bib
link-citations: yes
link-at-notes: true
knit: (function(inputFile, encoding) {
      out_dir <- "output";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path("../",dirname(inputFile), out_dir))})
---

# Fisica Nucleare {#fisica-nucleare}

## Le unità di misura della Fisica Nucleare e Subnucleare

La scelta della unità di misura è arbitraria ma, in accordo con i criteri che ispirano i moderni sistemi, soddisfa alcuni semplici requisiti di ordine generale:

-   **l'unità deve essere connessa ad un fenomeno naturale ritenuto stabile ed invariabile nel tempo** piuttosto che ad un oggetto o manufatto particolare il quale potrebbe deteriorarsi o modificare le sue proprietà con il tempo;
-   **le unità non devono essere ridondanti** e devono costituire un sistema di grandezze fisiche irriducibili dette fondamentali dalle quali ottenere tutte le altre che invece vengono dette derivate;
-   **l'unità deve essere riproducibile in laboratorio con una relativa facilità** (in realtà è lavoro da professionisti quali sono i metrologi).

Un sistema di unità di misura più appropriato può essere costruito facendo riferimento alle costanti fisiche fondamentali che governano i fenomeni nucleari e subnucleari. Accanto alle grandezze fondamentali, ogni area della fisica introduce anche specifiche costanti fisiche.

Queste possono essere sia dimensionali che adimensionali, riferirsi a specifiche classi di fenomeni - e dunque di *rango locale* - oppure valide per ogni fenomeno fisico e quindi di *rango universale*. Mentre il valore numerico delle costanti dimensionali dipende dalla scelta del sistema di unità misura, quello delle costanti adimensionali ne è del tutto indipendente per cui si ritiene che siano dotate di un più profondo significato fisico anche se a tutt'oggi nessuna teoria è in grado di predirne il valore.

Fu Planck che propose di assumere come grandezze fisiche fondamentali le costanti fisiche universali introducendo i cosiddetti sistemi naturali di unità di misura. Lo scopo di tali sistemi è quello di dedurre le appropriate scale di lunghezze, tempi, masse e temperature direttamente dai fenomeni naturali piuttosto che da convenzioni di natura metrologica

<!-- [in un celebre articolo presentato nel 1899 all’accademia di Berlino, Planck sviluppò un Sistema Naturale basato sulle costanti universali G (costante di gravitazione), k (costante di Boltzmann), c (velocità della luce) ed h (costante di Planck)]. -->

La costruzione di un sistema di unità di misura le cui grandezze abbiano la scala appropriata per una certa classe di fenomeni richiede l'introduzione di specifici vincoli tra le grandezze fondamentali della descrizione macroscopica. Ad esempio, dato che **i fenomeni nucleari e subnucleari sono al tempo stesso relativistici e quantistici** ciò significa che le velocità, ovvero i quozienti tra lunghezze e tempi saranno dell'ordine di c, mentre le azioni, cioè i prodotti delle energie per i tempi caratteristici saranno dell'ordine di $\hslash$. Due costanti universali non sono però sufficienti per fissare la scala delle tre grandezze necessarie al Sistema Internazionale per descrivere la relatività e meccanica quantistica (L, T ed M). Il particolare ruolo giocato dalle macchine acceleratrici in fisica nucleare e delle particelle elementari suggerisce allora di assumere come terza grandezza (non costante) un fondamentale parametro costruttivo della macchina, **l'energia E**. In accordo con le convenzioni adottate nella ingegneria delle macchine acceleratrici si assume come unità l'elettronvolt (eV), ovvero l'energia cinetica acquisita da un elettrone accelerato da una differenza di potenziale di un volt. Si ottiene facilmente la sua conversione in joule: $E_\text{cin} = eV$ da cui $1 eV = 1.602 \times 10^{-19} \ J$.

Definite le unità del **Sistema Naturale della Fisica Nucleare e Subnucleare (SNNS)** possiamo facilmente calcolare i loro valori nel Sistema Internazionale (SI) attraverso le seguenti equazioni dimensionali (si noti che con le lettere minuscole indichiamo le grandezze fondamentali del SNNS e con le maiuscole quelle del SI) $$
      c \sim \frac{L}{T} \qquad \epsilon \sim M c^2 \qquad \epsilon T \sim \hslash
$$ $$
       L \sim cT \qquad M \sim \frac{\epsilon}{c^2} \qquad T \sim \frac{\hslash}{\epsilon}
$$ $$
     \Longrightarrow L \sim \frac{\hslash c}{\epsilon} \qquad M \sim \frac{\epsilon}{c^2} \qquad T \sim           \frac{\hslash}{\epsilon}
$$ Da queste deduciamo che le lunghezze possono essere misurate in unità di $\frac{\hslash c}{\epsilon}$ ($\hslash c / eV$ o $1/eV$ se $ħ=c=1$), i tempi in unità di $\frac{\hslash}{\epsilon}$ ($\hslash/eV$ o $1/eV$ se $\hslash=1$) ed infine le masse in unità di $\epsilon/c^2(eV/c^2$ o $eV$ se $c=1$).

Tenendo ora presenti i valori delle costanti universali espresse nel Sistema Internazionale e della conversione tra Joule ($J$) ed elettronvolt ($eV$): $$
    \hslash = 1.055 \times 10^{-34} J \cdot s \quad c = 2.998 \times 10^8 m/s \quad \hslash c = 3.162 \times 10^{-26} J \cdot m
$$ $$
     \qquad \quad 1 eV = 1.602 \times 10^{-19} J
$$ possiamo calcolare i coefficienti della conversione tra il Sistema Naturale della Fisica Nucleare e Subnucleare ed il Sistema Internazionale (per quanto riguarda l'energia, piuttosto che gli eV, assumeremo la scala più appropriata dei MeV) $$
      L \sim \frac{\hslash c}{\epsilon} \qquad 1 \left(\frac{\hslash c}{MeV}\right) \sim 1.97      \times 10^{-19} m 
$$ $$
     M \sim \frac{\epsilon}{c^2} \qquad 1 \left(\frac{MeV}{c^2}\right) \sim 1.78 \times 10^{-30} Kg
$$ $$
     \frac{\hp}{\epsilon} \sim T \qquad 1 \left ( \frac{\hp}{MeV} \right) \sim 6.59 \times 10^{-22} s
$$

## Le proprietà generali dei nuclei

Il **nucleo** è un sistema composto formato da **neutroni** e **protoni** -- spesso indicati con il nome generico di **nucleoni** - tenuti assieme dalla **interazione forte**, una delle interazioni fondamentali della natura(di cui non si ha traccia macroscopicamente).

In fisica nucleare si usa il termine 'nuclide' piuttosto che 'nucleo' più prossimo alla chimica. Si hanno le seguenti grandezze rilevanti:

-   **numero atomico** $Z$, ovvero numero di protoni del nuclide ;
-   il numero di neutroni non ha nome specifico e si indica con $N$;
-   **numero di massa** $A$, ovvero il numero di nucleoni $Z+N$.

Ne consegue che una qualunque coppia dei numeri $Z, N$ ed $A$ identifica univocamente il nuclide. La notazione è la seguente: $$
        \mathlarger{\mathlarger{^A_ZX}}_N
$$

Si parla di nuclidi

1.  **isotopi** se hanno stesso $Z$ ma diversi $N$ ed $A$;
2.  **isotoni** se hanno stesso $N$ ma diversi $Z$ ed $A$;
3.  **isobari** se hanno stesso $A$ ma diversi $N$ ed $Z$;
    -   se questi hanno $N$ e $Z$ scambiati si dicono *speculari*;
4.  **isomeri** se sono identici ma in uno stato di energia differente.

Il neutrone ha una massa di $939.56 MeV/c^2$ che eccede di soli $1.29 MeV\c^2$ la massa del protone che ammonta a $938.27 MeV/c^2$. Spesso approssimate a $940 MeV$ o addirittura ad $1 GeV/c^2$, i nucleoni risultano circa $1840$ volte più massivi dell'elettrone ($0.51 MeV/c^2$). La piccola differenza di massa gioca un ruolo chiave in molti fenomeni (vedi [paragrafo](##la-differenza-di-massa-tra-neutrone-e-protone) sulla differenza di massa neutrone-protone).

Sia i **neutroni** che i protoni possiedono un momento angolare intrinseco di **spin** $s=\frac{1}{2}$ (in unità $\hp$). Sulla base della meccanica quantistica, ciò significa che la proiezione del momento angolare lungo un certo asse può assumere i due soli valori $\frac{1}{2} \hp$ e $-\frac{1}{2}\hp$. Lo spin interviene non solo negli aspetti specifici della dinamica dei nucleoni ma anche nella determinazione del loro **comportamento collettivo**. La meccanica quantistica impone ai sistemi di particelle identiche restrizioni peculiari che non hanno analogie nella fisica classica. Sulla base del **teorema spin statistica** i neutroni ed i protoni nucleari - che hanno spin semintero - si comportano collettivamente come **fermioni** e devono soddisfare il **principio di Pauli**, un fatto che gioca un ruolo decisivo nella **stabilità** e **struttura** del nucleo.

```{marginfigure,echo=TRUE}
    Momento di dipolo magnetico dei nucleoni
```

Nella fisica classica solo una particella estesa può possedere momento angolare intrinseco (spin). Se lo possiede ed è elettricamente carica allora possiede anche momento di dipolo magnetico. Ad esempio è facile mostrare che un anello di carica $‘e’$ e superficie $S$, posto in rotazione attorno all'asse di simmetria, soddisfa la seguente relazione $\mu = e L$.

Nella fisica quantistica, non solo le particelle estese (composte) ma **anche quelle puntiform**i (elementari) possono essere dotate di **spin** per cui - se dotate di carica elettrica - possiederanno anche un **momento di dipolo magnetico**.

Vediamo da un conto esplicito che l'analogia classica-quantistica è fallimentare: $$
      \mu = i S = \frac{e}{T}\pi R^2 \rightarrow L = mvR = m \frac{2 \pi R}{T}R
$$ 
$$
             \pi R^2 = \frac{T}{2m}L \rightarrow \mu = \frac{e}{T}\frac{T}{2m}L = \frac{e \hp}{2m}\left( \frac{L}{\hp}\right) 
$$ dove la grandezza $\frac{e \hp}{2m}$ viene detta **magnetone di Bohr** e vale $9.274\times 10^{−24}J/T$. E' un fatto ben noto però che la relazione tra $\mu$ ed $L$ differisce da quella classica per un fattore numerico. Ad esempio, nel caso di particelle puntiformi di spin $1⁄2$, l'equazione **quantomeccanica relativistica di Dirac** conduce ad una relazione contenente un fattore $g$ di valore $2$.

Preso atto di questo fatto dobbiamo aggiungere che le teorie di campo quantizzato hanno dimostrato che il fattore g=2 delle particelle puntiformi deve subire **piccole correzioni** dovute a certi processi virtuali, soprattutto di natura elettromagnetica, di cui diremo $$
       g = 2(1+a) \qquad a = \frac{g -2}{2}
$$ La correzione $a$ - detta *momento magnetico anomalo* o anche $\frac{g -2}{2}$ - rappresenta uno dei parametri più importanti per un confronto di alta precisione tra previsioni teoriche e misure sperimentali. A titolo di esempio nel caso dell'elettrone si ha $$
    a_{th} =  0.001 159 652 181 643 (764)
$$ $$
     a_{ex} = 0.001 159 652 180 730 (280)
$$ lo stupefacente accordo costituisce uno dei test più significativi a favore della QED.

Nel caso in cui la particella quantistica non sia puntiforme il fattore $g=2$ si modifica ben più pesantemente. Ad esempio, nel caso del protone deve essere moltiplicato per $2.79$per cui si ha $g=2 \times 2.79=5.58$ mentre nel caso del neutrone deve essere moltiplicato per $-1.91$per cui si ha $g=2 \times(-1.91) = -3.82$.

Tali valori così diversi dal fattore 2 delle particelle puntiformi dimostrano la natura non elementare dei nucleoni, un fatto che troverà la sua conferma nel modello a quark degli adroni.

I nucleoni non possiedono invece momento di dipolo elettrico un fatto che ha importanti implicazioni sulle quali torneremo.

Il modello a quark degli adroni (particelle soggette alla interazione forte) chiarisce che i nucleoni non sono particelle elementari. Tralasciando per ora la complessa struttura prevista dalla teoria dei campi quantizzati, in prima approssimazione i nucleoni sono pensabili come **stati legati di tre quark** (i quark costituiscono una famiglia di 6 particelle elementari del modello standard) con 'carica forte' complessiva nulla (nel gergo della QCD di colore bianco) nello stato di minima energia. In particolare neutrone e protone sono stati legati dei quark (u, d, d) e (u, u, d) rispettivamente.

La natura composta dei nucleoni chiarisce anche la natura della forza forte che li lega all'interno del nucleo. Infatti, oggi sappiamo che le vere sorgenti della interazione forte sono le 'cariche forti' (cariche di colore) dei tre quark che compongono i nucleoni per cui la forza forte che li unisce nei nuclidi altro non è che il residuo esterno della interazione forte primaria tra i quark. Per questo motivo la forza forte tra nucleoni ha una struttura complicata e decade rapidamente con la distanza assumendo un carattere a **corto raggio**.

Da questo punto di vista è assai utile l'analogia con le forze elettromagnetiche nelle molecole, le forze di Van der Waals. Le interazioni primarie tra le cariche dei nuclei e degli elettroni interni alla molecola sono le interazioni elettromagnetiche a lungo raggio caratterizzate da una struttura relativamente semplice. All'esterno della molecola però, si osserva la risultante di tali interazioni che è attrattiva, ha un andamento spaziale complicato e decade rapidamente con la distanza.

In questo senso possiamo affermare che **le forze forti tra nucleoni sono le forze di Van der Waals delle interazioni forti tra i quarks**. Premesso che la comprensione delle forze forti tra nucleoni a partire dalle sottostanti interazioni forti tra quarks mediate da gluoni è un tema di assoluta frontiera non ancora risolto (QCD), il carattere essenzialmente **attrattivo** e a **corto raggio** della **forza forte** tra nucleoni è noto sin dagli anni '30.

[pag. 18-21 come approfondimento dalle dispense]

## La differenza di massa tra neutrone e protone

pag 21-23 dispense

## Le carte dei nuclidi

qui roba lezione 3 <!-- TODO -->
